"""
Research Digest Renderer
=========================
Renders research results into multiple output formats for the
Autonomous Research Blueprint system.

Supported formats:
    - Markdown (for file/Telegram delivery)
    - JSON (for downstream processing/APIs)
    - HTML (for email digests)
"""

import json
import logging
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger("hermes.scheduler.digest_renderer")


class DigestRenderer:
    """
    Renders a list of ResearchItems into a formatted digest.

    Supports deduplication, grouping by source, and relevance-based ordering.
    """

    def render(self, blueprint, items: list, output_format: str = "markdown",
               execution_time: str = None) -> str:
        """
        Render items into the specified format.

        Args:
            blueprint:      The ResearchBlueprint that produced these items
            items:          List of ResearchItem objects
            output_format:  "markdown" | "json" | "html"
            execution_time: ISO timestamp of when execution started
        """
        if output_format == "json":
            return self._render_json(blueprint, items, execution_time)
        elif output_format == "html":
            return self._render_html(blueprint, items, execution_time)
        else:
            return self._render_markdown(blueprint, items, execution_time)

    # -------------------------------------------------------------------
    # Markdown
    # -------------------------------------------------------------------

    def _render_markdown(self, blueprint, items: list,
                         execution_time: str = None) -> str:
        now = execution_time or datetime.now(timezone.utc).isoformat()
        lines = [
            f"# 📋 Research Digest: {blueprint.name}",
            f"",
            f"> **{blueprint.description}**",
            f"",
            f"**Generated:** {now}  ",
            f"**Sources:** {', '.join(blueprint.sources)}  ",
            f"**Keywords:** {', '.join(blueprint.keywords)}  ",
            f"**Items found:** {len(items)}  ",
            f"",
            f"---",
            f"",
        ]

        if not items:
            lines.append("*No items found matching your criteria.*")
            return "\n".join(lines)

        # Group by source
        sources = {}
        for item in items:
            sources.setdefault(item.source, []).append(item)

        source_icons = {
            "arxiv": "📄",
            "github": "🐙",
            "reddit": "💬",
            "web": "🌐",
        }

        for source, source_items in sources.items():
            icon = source_icons.get(source, "📌")
            lines.append(f"## {icon} {source.upper()} ({len(source_items)} items)")
            lines.append("")

            for i, item in enumerate(source_items, 1):
                relevance_bar = self._relevance_bar(item.relevance_score)
                lines.append(f"### {i}. [{item.title}]({item.url})")
                lines.append(f"**Relevance:** {relevance_bar} ({item.relevance_score:.1%})")

                if item.authors:
                    lines.append(f"**Authors:** {item.authors}")
                if item.published:
                    lines.append(f"**Published:** {item.published[:10]}")

                lines.append(f"")
                lines.append(f"{item.summary}")
                lines.append(f"")
                lines.append(f"---")
                lines.append(f"")

        # Footer
        lines.extend([
            f"",
            f"---",
            f"*Report generated by Hermes Agent Research Blueprint: `{blueprint.name}`*  ",
            f"*Schedule: `{blueprint.schedule}` | Run #{blueprint.run_count + 1}*",
        ])

        return "\n".join(lines)

    # -------------------------------------------------------------------
    # JSON
    # -------------------------------------------------------------------

    def _render_json(self, blueprint, items: list,
                     execution_time: str = None) -> str:
        now = execution_time or datetime.now(timezone.utc).isoformat()
        output = {
            "metadata": {
                "blueprint_name": blueprint.name,
                "description": blueprint.description,
                "generated_at": now,
                "sources": blueprint.sources,
                "keywords": blueprint.keywords,
                "total_items": len(items),
                "schedule": blueprint.schedule,
                "run_number": blueprint.run_count + 1,
            },
            "items": [
                {
                    "title": item.title,
                    "url": item.url,
                    "summary": item.summary,
                    "relevance_score": item.relevance_score,
                    "source": item.source,
                    "published": item.published,
                    "authors": item.authors,
                    "metadata": item.metadata,
                }
                for item in items
            ],
        }
        return json.dumps(output, indent=2, ensure_ascii=False)

    # -------------------------------------------------------------------
    # HTML
    # -------------------------------------------------------------------

    def _render_html(self, blueprint, items: list,
                     execution_time: str = None) -> str:
        now = execution_time or datetime.now(timezone.utc).isoformat()

        source_colors = {
            "arxiv": "#b31b1b",
            "github": "#24292e",
            "reddit": "#ff4500",
            "web": "#4285f4",
        }

        items_html = []
        for item in items:
            color = source_colors.get(item.source, "#666")
            pct = f"{item.relevance_score:.0%}"
            authors_line = f'<p class="authors">👤 {item.authors}</p>' if item.authors else ""
            pub_line = f'<span class="date">📅 {item.published[:10]}</span>' if item.published else ""

            items_html.append(f"""
            <div class="item">
                <div class="item-header">
                    <span class="source-badge" style="background:{color}">{item.source.upper()}</span>
                    <span class="relevance">{pct}</span>
                    {pub_line}
                </div>
                <h3><a href="{item.url}" target="_blank">{item.title}</a></h3>
                {authors_line}
                <p class="summary">{item.summary}</p>
            </div>
            """)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Research Digest: {blueprint.name}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #0f0f23;
            color: #e0e0e0;
            padding: 2rem;
            line-height: 1.6;
        }}
        .header {{
            text-align: center;
            padding: 2rem 0;
            border-bottom: 1px solid #333;
            margin-bottom: 2rem;
        }}
        .header h1 {{
            font-size: 1.8rem;
            background: linear-gradient(135deg, #667eea, #764ba2);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }}
        .meta {{ color: #888; font-size: 0.9rem; margin-top: 0.5rem; }}
        .item {{
            background: #1a1a2e;
            border: 1px solid #333;
            border-radius: 12px;
            padding: 1.5rem;
            margin-bottom: 1rem;
            transition: transform 0.2s;
        }}
        .item:hover {{ transform: translateY(-2px); border-color: #667eea; }}
        .item-header {{
            display: flex;
            gap: 0.75rem;
            align-items: center;
            margin-bottom: 0.75rem;
        }}
        .source-badge {{
            color: white;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 0.7rem;
            font-weight: bold;
            text-transform: uppercase;
        }}
        .relevance {{
            color: #667eea;
            font-weight: bold;
            font-size: 0.85rem;
        }}
        .date {{ color: #888; font-size: 0.8rem; }}
        h3 {{ margin-bottom: 0.5rem; }}
        h3 a {{ color: #8fa4f0; text-decoration: none; }}
        h3 a:hover {{ color: #a5b4fc; text-decoration: underline; }}
        .authors {{ color: #aaa; font-size: 0.85rem; margin-bottom: 0.5rem; }}
        .summary {{ color: #ccc; font-size: 0.9rem; }}
        .footer {{
            text-align: center;
            padding: 2rem 0;
            color: #666;
            font-size: 0.8rem;
            border-top: 1px solid #333;
            margin-top: 2rem;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📋 {blueprint.name}</h1>
        <p class="meta">{blueprint.description}</p>
        <p class="meta">
            Generated: {now[:19]} | Sources: {', '.join(blueprint.sources)} |
            {len(items)} items found
        </p>
    </div>

    {"".join(items_html) if items_html else '<p style="text-align:center;color:#888;">No items found.</p>'}

    <div class="footer">
        Hermes Agent Research Blueprint: {blueprint.name}<br>
        Schedule: {blueprint.schedule} | Run #{blueprint.run_count + 1}
    </div>
</body>
</html>"""

    # -------------------------------------------------------------------
    # Helpers
    # -------------------------------------------------------------------

    @staticmethod
    def _relevance_bar(score: float, width: int = 10) -> str:
        """Generate a visual relevance bar (e.g. ████████░░)."""
        filled = round(score * width)
        empty = width - filled
        return "█" * filled + "░" * empty
